spring.application.name=GymFuelApp
spring.datasource.url=jdbc:postgresql://localhost:5432/GymFuel
spring.datasource.username=postgres
spring.datasource.password=Anime_123

##.port=4200

# Show the "message" field in the error JSON
server.error.include-message=always
# Show the "errors" list (the specific field errors) in the JSON
server.error.include-binding-errors=always
#local
allowed.origins=http://localhost:4200
# application.properties
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# test with phone
#allowed.origins=https://poultry-standings-drill-tonight.trycloudflare.com


#346730978765-6ta6iuel5d9lipkmv4f2e0hfgm1cc32s.apps.googleusercontent.com

#netstat -ano | findstr :8080
#taskkill /F /PID 5488
