spring.application.name=GymFuelApp
spring.datasource.url=jdbc:postgresql://localhost:5432/GymFuel
spring.datasource.username=postgres
spring.datasource.password=Anime_123

# Show the "message" field in the error JSON
server.error.include-message=always
# Show the "errors" list (the specific field errors) in the JSON
server.error.include-binding-errors=always


